Use precompiled deps
membraneframework/membrane_opus_plugin pull request #48
Opened 2023-10-03 12:41 UTC by DominikWolek

2023-10-04 09:21 UTC, mat-hek requested changes

2023-10-04 09:21 UTC, mat-hek commented on bundlex.exs
> +        os_deps: [{get_opus_url(), "opus"}],
you should add the fallback to `:pkg_config` everywhere

2023-10-09 09:39 UTC, Noarkhh requested changes
Like in `membrane_ffmpeg_video_filter_plugin`, readme and version

2023-10-09 12:14 UTC, Noarkhh approved these changes

2023-10-09 13:55 UTC, mat-hek approved these changes

2023-10-09 15:16 UTC, merged