Opus encoder outputting non-monotonic PTS
membraneframework/membrane_opus_plugin pull request #64
Opened 2024-07-17 11:18 UTC by bartkrak

related to: https://github.com/membraneframework/membrane_core/issues/834

2024-07-24 15:51 UTC, FelonEkonom requested changes
Refresh me when you implement the changes that we spoke about in the office

2024-08-07 10:32 UTC, FelonEkonom commented
> @FelonEkonom Dialyzer fails on the part of code that didn't change in this pr, Do you know how to fix this? I looked at the previous release and it was passing.

Errors produced by Dialyzer often don't relate do the exact place, that causes the problem, so it still might be caused by your changes. 

Dialyzer fail here might be also caused by Elixir version bump, so I recommend you running Dialyzer on current `master` with Elixir 1.17.2, to check it

2024-08-07 10:38 UTC, FelonEkonom requested changes

2024-08-07 10:38 UTC, FelonEkonom commented on lib/membrane_opus/encoder.ex
> +      diff = (state.current_pts - input_pts) |> Time.nanoseconds()
if `state.current_pts` and `input_pts` are `Membrane.Time.t()`, there is no need to pass the difference between them to `Membrane.Time.nanoseconds/1`

2024-08-07 10:38 UTC, FelonEkonom commented on lib/membrane_opus/encoder.ex
> +          )
Print diff only one (or in `ms`, or as result of `Time.pretty_duration`)
Add to the log expected value (`state.current_pts`) and value that occurs in the input buffer

2024-08-08 10:34 UTC, mat-hek commented
@FelonEkonom it seems it helps, as when I updated MP4 and Opus in boombox, tests passed, though I get a bunch of 
```
12:30:22.171 [warning] <0.672.0>/:webrtc_out_opus_encoder PTS values are overlapping
```

To reproduce, get boombox from `update-deps` branch and run `mix test` or `mix test --only webrtc_audio`

2024-08-09 13:35 UTC, FelonEkonom commented
@mat-hek such a branch doesn't exist in `boombox`

2024-08-09 13:57 UTC, FelonEkonom approved these changes
@bartkrak according to what @mat-hek wrote, let's merge it as it is now and create an issue describing problem with warnings that occurs in boombox with opus plugin

2024-08-23 09:27 UTC, mat-hek requested changes

2024-08-23 09:27 UTC, mat-hek commented on lib/membrane_opus/util.ex
> +      epsilon = 30 |> milliseconds()
As we spoke, the actual overlap is no more than 2ms. Try refactoring it so that we operate on the actual overlap.

2024-08-29 07:50 UTC, mat-hek approved these changes

2024-08-29 13:32 UTC, merged